apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maptdp-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jaffleman/maptdp-gitops.git'
    targetRevision: main
    path: apps/infra/apps/maptdp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: maptdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true