all:
  children:
    k3s_nodes:
      hosts:
        vps-ovh1:
          ansible_host: 146.59.231.136
          ansible_user: ubuntu
        # vps-ovh2:
        #   ansible_host: 137.74.118.17
        #   ansible_user: ubuntu