apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: maptdp-db-sync
  namespace: maptdp-prod
spec:
  vaultAuthRef: vault-jwt-auth
  mount: k3s
  path: maptdp/db
  type: kv-v2

  refreshInterval: 5m

  destination:
    name: maptdp-db-auth
    namespace: maptdp-prod
    create: true