apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth

metadata:
  name: vault-jwt-auth
  namespace: argocd

spec:
  vaultConnectionRef: vault-connection-maptdp

  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: argocd-role
