apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-jwt-auth
  namespace: maptdp
spec:
  vaultConnectionRef: vault-connection-maptdp
  method: kubernetes
  mount: k8s-prod

  kubernetes:
    role: db-role
    serviceAccount: vso-app-sa