apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: maptdp-db-sync
  namespace: maptdp
spec:
  vaultAuthRef: vault-jwt-auth
  mount: kv-aws
  path: maptdp/prod/rds-config
  type: kv-v2

  refreshInterval: 5m

  destination:
    name: maptdp-db-auth
    create: true