apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret

metadata:
  name: dockerhub-secret-sync
  namespace: argocd

spec:
  vaultAuthRef: vault-jwt-auth

  mount: k3s
  path: maptdp/dockerhub
  type: kv-v2

  refreshInterval: 5m

  destination:
    name: dockerhub-secret
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson

    transformation:
      excludeRaw: true

      templates:
        .dockerconfigjson:
          text: |
