apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: velero-s3-sync
  namespace: velero

spec:
  vaultAuthRef: vault-velero-backup-auth

  mount: backups
  path: postgres-s3
  type: kv-v2

  refreshAfter: 5m

  destination:
    name: velero-s3-auth
    create: true
