apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-s3-sync
  namespace: maptdp-staging

spec:
  vaultAuthRef: vault-postgres-backup-auth

  mount: backups
  path: postgres-s3
  type: kv-v2

  refreshInterval: 5m

  destination:
    name: postgres-s3-auth
    create: true
