apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth

metadata:
  name: vault-jwt-auth
  namespace: maptdp-staging

spec:
  vaultConnectionRef: vault-connection-backup

  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: postgres-backup-role
    serviceAccount: postgres-backup-sa
