apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-postgres-backup-auth
  namespace: maptdp-staging
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: postgres-backup-role
    serviceAccount: postgres-backup-sa
  vaultConnectionRef: vault-connection-maptdp
