apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-postgres-backup-auth
  namespace: maptdp-staging

spec:
  vaultConnectionRef: vault-connection-maptdp

  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: postgres-backup-role
    serviceAccount: vso-app-sa
