apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-s3-secret
  namespace: maptdp-staging
spec:
  type: kv-v2
  mount: backups
  path: postgres-s3

  destination:
    name: postgres-s3-secret
    create: true

  vaultAuthRef: vault-postgres-backup-auth

  refreshAfter: 1h
