apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret

metadata:
  name: monitoring-secret-sync
  namespace: monitoring

spec:
  vaultAuthRef: vault-jwt-auth

  mount: k3s
  path: maptdp/grafana
  type: kv-v2

  refreshInterval: 5m

  destination:
    name: monitoring-auth
    create: true
