apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret

metadata:
  name: argocd-repo-github-sync
  namespace: argocd

spec:
  vaultAuthRef: vault-jwt-auth

  mount: kv-aws
  path: maptdp/prod/gitops-repo
  type: kv-v2

  refreshInterval: 5m

  destination:
    name: argocd-repo-github
    create: true
    overwrite: true

    labels:
      argocd.argoproj.io/secret-type: repository