apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dockerhub-creds
  namespace: argocd

spec:
  vaultAuthRef: vault-jwt-auth

  type: kv-v2
  mount: kv-aws
  path: maptdp/prod/docker-hub-creds

  destination:
    name: dockerhub-creds
    create: true
    type: Opaque

  refreshAfter: 1h