--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- Note : Les rôles et privilèges globaux superutilisateurs ont été retirés 
-- car ils sont managés directement par AWS RDS.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: geolockbdd; Type: DATABASE; Schema: -; Owner: CURRENT_USER
--

CREATE DATABASE geolockbdd;

\connect geolockbdd

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Name: acces; Type: TABLE; Schema: public; Owner: CURRENT_USER
--

CREATE TABLE public.acces (
    id integer NOT NULL,
    type text,
    code text NOT NULL,
    mk integer NOT NULL
);

--
-- Name: acces_id_seq; Type: SEQUENCE; Schema: public; Owner: CURRENT_USER
--

ALTER TABLE public.acces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: marker; Type: TABLE; Schema: public; Owner: CURRENT_USER
--

CREATE TABLE public.marker (
    id integer NOT NULL,
    longitude integer NOT NULL,
    latitude integer NOT NULL,
    author text,
    adresse text,
    "accesNbr" integer,
    "createdDate" date
);

--
-- Name: marker_id_seq; Type: SEQUENCE; Schema: public; Owner: CURRENT_USER
--

ALTER TABLE public.marker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Data for Name: acces; Type: TABLE DATA; Schema: public; Owner: CURRENT_USER
--
INSERT INTO public.acces (id, type, code, mk) VALUES
(1, 'Portail', 'INCO', 0),
(2, 'Barrière', '0000', 2),
(3, 'Barrière', '0000', 3),
(4, 'Portail', 'INCO', 4),
(5, 'Deuxième porte', '75A74', 5),
(6, 'Bâtiment 🏢', 'INCO', 6),
(7, 'Bâtiment', 'INCO', 7),
(8, 'Bâtiment A 🏢', 'INCO', 8),
(9, 'Bâtiment 🏢', '3645', 9),
(10, 'Bâtiment 🏢', '3086B', 10),
(11, 'Barriere', '153824', 11),
(12, 'Barrière', '3686', 12),
(13, 'Bâtiment 🏢', '3686', 12),
(14, 'Portails', 'B8356', 13),
(15, 'Bâtiment 🏢', '1536', 14),
(16, 'Bâtiment', '8A170', 15),
(17, 'Bâtiment', '2960', 16),
(18, 'Escalier 2', 'INCO', 17),
(19, 'Bâtiment 🏢', '2910', 18),
(20, 'Bâtiment 🏢', 'INCO', 19),
(21, '2eme porte', 'INCO', 19),
(22, 'Barrière', 'INCO', 20),
(23, 'Barrière', 'INCO', 21),
(24, 'Bâtiment 🏢', 'INCO', 22),
(25, 'Bâtiment 🏢', '5273', 0),
(26, 'Bâtiment 🏢', '5273', 0),
(27, 'Bâtiment 🏢', '5273', 0),
(28, 'Bâtiment ', '2357', 25),
(29, 'Bâtiment ', 'B2703', 26),
(30, 'Grille ', 'B2703', 26),
(31, 'Bâtiment 🏢 ', '7458', 27),
(32, '2ème Porte', '5628', 27),
(33, '2eme porte', '5628', 27),
(34, 'Barrière ', 'INCO', 28),
(35, 'Bâtiment B', '8256B', 28),
(36, 'Bâtiment 🏢', '9B316', 29),
(37, 'Bâtiment 🏢', '9B3A6', 30),
(38, 'Bâtiment 🏢', 'INCO', 31),
(39, 'Barrière ', 'INCO', 32),
(40, 'Bâtiment 🏢', '9812', 33),
(41, 'Bâtiment 🏢', '1950', 34),
(42, 'Barrière ', 'INCO', 35),
(43, 'Bâtiment 🏢', 'INCO', 35),
(44, 'Bâtiment 🏢', '1536', 0),
(45, 'Bâtiment 🏢', '1536', 0),
(46, 'Bâtiment 🏢', '25A89', 37),
(47, 'Bâtiment 🏢', '97A6', 38),
(48, 'Barrière ', '2003', 39),
(49, 'Bâtiment A ', '2003', 39),
(50, 'Bâtiment 🏢 ', 'INCO', 40),
(51, 'Bâtiment 🏢 ', '2805A', 41),
(52, 'Bâtiment 🏢 ', '2021', 42),
(53, 'Barrière ', '1421', 43),
(54, 'Bâtiment 🏢 ', '0107', 43),
(55, 'Bâtiment 🏢 ', 'INCO', 44),
(56, 'Bâtiment 🏢 ', '5271', 45),
(57, '2eme porte ', '2859', 46),
(58, 'Bâtiment 🏢 ', '1845', 47),
(59, 'Barrière ', 'INCO', 48),
(60, 'Bâtiment 🏢 ', 'INCO', 48),
(61, 'Barrière ', 'INCO', 49),
(62, 'Bâtiment 🏢 ', 'INCO', 49),
(63, 'Portillon noir', '4994A', 50),
(64, 'Bâtiment 🏢 ', 'A1777', 51),
(65, 'Bâtiment 🏢 ', '9672', 52),
(66, 'Barrière ', 'INCO', 53),
(67, 'Bâtiment 🏢 ', '14A70', 54),
(68, 'Ascenseur', '28B35', 55),
(69, 'Bâtiment 🏢 ', 'B674', 56),
(70, '2ème Porte', '74B04', 57),
(71, 'Barrière ', 'INCO', 58),
(72, 'Bâtiment ', '5273', 59),
(73, 'Barrière ', '1534', 60),
(74, 'Bâtiment 🏢 ', '01B10', 61),
(75, 'Bâtiment 🏢 ', 'INCO', 62),
(76, 'Bâtiment 🏢 ', '1003', 63),
(77, 'Bâtiment 🏢 ', '6823B8', 64),
(78, 'Bâtiment 🏢 ', '19429', 65),
(79, 'Bâtiment 🏢 ', '7613', 66),
(80, '2ème Porte', 'BBBBBB', 67),
(81, '2ème Porte', '13081', 68),
(82, 'Bâtiment 🏢 ', '32A49', 69),
(83, 'Barrière ', '3845', 70),
(84, '2ème Porte', '19BB19', 71),
(85, '2ème ', '19BB19', 72),
(86, 'Portillon ', '7529', 73),
(87, 'Bâtiment ', '1107', 73),
(88, 'Bâtiment 🏢 ', 'BA2760', 74),
(89, 'Bâtiment ', 'INCO', 75),
(90, 'Bâtiment 🏢 ', '2024', 76),
(91, '2ème Porte', '2024', 76),
(92, 'Barrière', 'AB2017', 77),
(93, '2ème Porte', 'AB2017', 77),
(94, 'Bâtiment', 'INCO', 78),
(95, 'Bâtiment 🏢', '1428', 79),
(96, '2eme porte', '2609', 79),
(97, 'Bâtiment 🏢', 'INCO', 80),
(98, 'Bâtiment 🏢', 'INCO', 0),
(99, 'Bâtiment 🏢', '1724', 81),
(100, 'Barrière', 'INCO', 82),
(101, 'Bâtiment 🏢', '28B56', 83),
(102, 'Bâtiment B ', '9602B', 83),
(103, 'Bâtiment 🏢 ', '1379', 84),
(104, 'Portillon ', '98A7', 85),
(105, 'Bâtiment c ', '29B11', 85),
(106, 'Barrière ', 'A5369', 86),
(107, 'Partout ', '4862', 87),
(108, 'Barrière ', '3257', 88),
(109, 'Partout ', '62431', 89),
(110, 'Bâtiment 🏢 ', 'INCO', 0),
(113, 'Bâtiment ', '3001', 92),
(114, 'Bâtiment 🏢 ', 'INCO', 0),
(115, 'Bâtiment 🏢 ', '95257', 94),
(116, 'Bâtiment ', 'INCO', 95),
(117, 'Bâtiment ', '1612A', 96),
(118, 'Bâtiment ', 'A936B', 97),
(119, 'Barrière ', 'INCO', 98),
(120, 'Bâtiment ', '4A16', 99),
(121, 'Ascenseur ', 'INCO', 99),
(122, 'Bâtiment 🏢 ', '943A2', 100),
(125, 'Barrière ', '64B97', 103),
(126, 'Bâtiment ', 'A342B', 104),
(127, 'Grille ', '65B34', 105),
(128, 'Barrière ', '7936', 106),
(129, 'Bâtiment ', '7936', 106),
(130, 'Bâtiment ', '8450', 107),
(131, 'Bâtiment 🏢 ', '96B54', 108),
(132, '2ème Porte', '96B45', 108),
(133, 'Bâtiment 🏢 ', '01A35', 109),
(134, 'Bâtiment 🏢 ', '3248', 110),
(135, '2ème porte', '3248', 110),
(136, 'Bâtiment 🏢 ', 'A1805', 111),
(137, '2ème ', 'A1805B', 111),
(138, 'Bâtiment 🏢 ', 'INCO', 112),
(139, 'Bâtiment 🏢 ', '6874', 113),
(140, 'Bâtiment 🏢 ', 'A0910', 114),
(141, 'Bâtiment 🏢 ', '2304', 115),
(142, 'Bâtiment A ', '2374A', 83),
(143, '2ème porte', 'INCO', 116),
(144, 'Bâtiment 🏢 ', '2971', 117),
(145, 'Bâtiment 🏢 ', '34B68', 118),
(146, '2eme porte', 'A1224B', 118),
(147, 'Barrière ', '15A84', 119),
(148, 'Bâtiment 🏢 ', 'INCO', 0),
(149, 'Portillon ', '16B06', 36),
(150, 'Batiment ', 'B0512', 36),
(151, 'Cours ', '04A31', 36),
(152, 'Ascenseur ', 'INCO', 36);

--
-- Data for Name: marker; Type: TABLE DATA; Schema: public; Owner: CURRENT_USER
--
INSERT INTO public.marker (id, longitude, latitude, author, adresse, "accesNbr", "createdDate") VALUES
(0, 0, 0, 'system', 'Unknown', NULL, '2025-01-01'),
(2, 258415, 4897349, 'Jaffleman', 'Espace Elysée', NULL, '2025-01-25'),
(3, 258362, 4897286, 'Jaffleman', 'Espace Elysée', NULL, '2025-01-25'),
(4, 235913, 4881364, 'Jaffleman', '32 Rue du Général Leclerc 94270 Le Kremlin-Bicêtre', NULL, '2025-01-29'),
(5, 236337, 4880733, 'Jaffleman', '141 Avenue de Fontainebleau 94270 Le Kremlin-Bicêtre', NULL, '2025-01-29'),
(6, 236771, 4879838, 'Jaffleman', '17 Boulevard Maxime Gorki 94800 Villejuif', NULL, '2025-01-30'),
(7, 235610, 4881374, 'Jaffleman', '11 Rue Édouard Vaillant 94270 Le Kremlin-Bicêtre', NULL, '2025-01-30'),
(8, 235924, 4878574, 'Jaffleman', '14 Rue Auguste Renoir 94800 Villejuif', NULL, '2025-01-30'),
(9, 235850, 4878676, 'Jaffleman', '2 Allée Rembrandt 94800 Villejuif', NULL, '2025-01-31'),
(10, 237019, 4879046, 'Jaffleman', '7 Rue de Bretagne 94800 Villejuif', NULL, '2025-01-31'),
(11, 236946, 4879057, 'Jaffleman', '7 RUE DE BRETAGNE\n94800 VILLEJUIF', NULL, '2025-01-31'),
(12, 235587, 4878907, 'Jaffleman', '8 Promenade Edouard Toulouse 94800 Villejuif', NULL, '2025-02-03'),
(13, 233985, 4879507, 'Jaffleman', '54 Rue Étienne Dolet 94230 Cachan', NULL, '2025-02-03'),
(14, 233789, 4879547, 'Jaffleman', '9 RUE COUSTE\n94230 CACHAN', NULL, '2025-02-04'),
(15, 235683, 4880268, 'Jaffleman', '11 Boulevard Chastenet de Géry 94800 Villejuif', NULL, '2025-02-05'),
(16, 236196, 4881525, 'Jaffleman', '7 Rue Pasteur 94270 Le Kremlin-Bicêtre', NULL, '2025-02-07'),
(17, 235540, 4877920, 'Jaffleman', '155 Rue de Chevilly 94800 Villejuif', NULL, '2025-02-10'),
(18, 235594, 4880216, 'Jaffleman', '4 Rue Marguerite Chapon 94800 Villejuif', NULL, '2025-02-10'),
(19, 235485, 4880318, 'Jaffleman', '2 Rue Marc Sangnier 94270 Le Kremlin-Bicêtre', NULL, '2025-02-11'),
(20, 236864, 4880141, 'Jaffleman', '64 Rue Émile Zola 94800 Villejuif', NULL, '2025-02-12'),
(21, 236258, 4880423, 'Jaffleman', '3 Allée des Alouettes 94800 Villejuif', NULL, '2025-02-12'),
(22, 234755, 4881309, 'Jaffleman', '4 Rue Bathilde 94250 Gentilly', NULL, '2025-02-12'),
(25, 233276, 4881077, 'Jaffleman', '57 Avenue Jean Jaurès 94110 Arcueil', NULL, '2025-02-14'),
(26, 236855, 4879625, 'Jaffleman', '47 Boulevard Maxime Gorki 94800 Villejuif', NULL, '2025-02-14'),
(27, 233840, 4879618, 'Jaffleman', '4 Rue Cousté 94230 Cachan', NULL, '2025-02-17'),
(28, 232850, 4880964, 'Jaffleman', '68 AVENUE LAPLACE\n94110 ARCUEIL', NULL, '2025-02-17'),
(29, 233123, 4880848, 'Jaffleman', '32 AVENUE LAPLACE 94110 ARCUEIL', NULL, '2025-02-18'),
(30, 233307, 4880812, 'Jaffleman', '32 AVENUE LAPLACE 94110 ARCUEIL', NULL, '2025-02-18'),
(31, 236659, 4879305, 'Jaffleman', '73 Rue Jean Jaurès 94800 Villejuif', NULL, '2025-02-18'),
(32, 236491, 4880666, 'Jaffleman', '16bis RUE PASTEUR 94800 Villejuif', NULL, '2025-02-19'),
(33, 233083, 4880978, 'Jaffleman', '18 AVENUE VLADIMIR ILITCH LENINE 94110 ARCUEIL', NULL, '2025-02-19'),
(34, 233593, 4880806, 'Jaffleman', '12 Villa Gustave Edouard 94110 Arcueil', NULL, '2025-02-20'),
(35, 236160, 4880721, 'Jaffleman', '37 à 39bis Rue Anatole France 94270 Le Kremlin-Bicêtre', NULL, '2025-02-20'),
(36, 239524, 4875862, 'Jaffleman', '3 cours Sainte Marthe 94320 Thiais', NULL, '2025-02-20'),
(37, 234873, 4881485, 'Jaffleman', '67 Rue Charles Frérot 94250 Gentilly', NULL, '2025-02-21'),
(38, 235698, 4878080, 'Jaffleman', '2 Allée des Bosquets 94800 Villejuif', NULL, '2025-02-21'),
(39, 235672, 4879457, 'Jaffleman', '50/54 Avenue Paul Vaillant-Couturier 94800 Villejuif', NULL, '2025-02-24'),
(40, 236538, 4880760, 'Jaffleman', '21 Rue Babeuf 94270 Le Kremlin-Bicêtre', NULL, '2025-02-24'),
(41, 233854, 4881383, 'Jaffleman', '34bis Rue des Champs Elysées 94250 Gentilly', NULL, '2025-02-24'),
(42, 235058, 4881239, 'Jaffleman', '11 Rue du Paroy 94250 Gentilly', NULL, '2025-02-25'),
(43, 233184, 4881415, 'Jaffleman', '7 Rue des Aqueducs 94250 Gentilly', NULL, '2025-02-26'),
(44, 236448, 4880930, 'Jaffleman', '14 Rue Carnot 94270 Le Kremlin-Bicêtre', NULL, '2025-02-26'),
(45, 233381, 4880252, 'Jaffleman', '43 Avenue de la Convention 94110 Arcueil', NULL, '2025-03-03'),
(46, 233295, 4881201, 'Jaffleman', '2 Rue de la Villa Mélanie 94110 Arcueil', NULL, '2025-03-03'),
(47, 235206, 4880615, 'Jaffleman', '15 Rue Léon Blum 94270 Le Kremlin-Bicêtre', NULL, '2025-03-04'),
(48, 233305, 4879026, 'Jaffleman', '54 Avenue Dumotel 94230 Cachan', NULL, '2025-03-04'),
(49, 236843, 4879672, 'Jaffleman', '41 Boulevard Maxime Gorki 94800 Villejuif', NULL, '2025-03-05'),
(50, 236957, 4879904, 'Jaffleman', '49bis Rue Bizet 94800 Villejuif', NULL, '2025-03-05'),
(51, 234827, 4880802, 'Jaffleman', '3 Rue John Fitzgerald Kennedy 94270 Le Kremlin-Bicêtre', NULL, '2025-03-07'),
(52, 237035, 4882969, 'Jaffleman', '10 Rue Xaintrailles 75013 Paris', NULL, '2025-03-11'),
(53, 237038, 4883218, 'Jaffleman', '8 Rue Duchefdelaville 75013 Paris', NULL, '2025-03-11'),
(54, 234902, 4883574, 'Jaffleman', '25/27 Boulevard Arago 75013 Paris', NULL, '2025-03-12'),
(55, 234954, 4883491, 'Jaffleman', 'unknow', NULL, '2025-03-12'),
(56, 237111, 4883252, 'Jaffleman', '153 Rue du Chevaleret 75013 Paris', NULL, '2025-03-13'),
(57, 237588, 4882752, 'Jaffleman', '66 Rue des Grands Moulins 75013 Paris', NULL, '2025-03-13'),
(58, 234433, 4882325, 'Jaffleman', '83 Rue Vergniaud 75013 Paris', NULL, '2025-03-14'),
(59, 233710, 4879399, 'Jaffleman', '20 Rue Guichard 94230 Cachan', NULL, '2025-03-18'),
(60, 232243, 4879274, 'Jaffleman', '16 Avenue du Pont-royal 94230 Cachan', NULL, '2025-03-19'),
(61, 235704, 4880299, 'Jaffleman', '15 Boulevard Chastenet de Géry 94800 Villejuif', NULL, '2025-03-19'),
(62, 233581, 4880926, 'Jaffleman', '33 Villa Baudran 94110 Arcueil', NULL, '2025-03-20'),
(63, 233264, 4879399, 'Jaffleman', '11/13 Rue Marx Dormoy 94230 Cachan', NULL, '2025-03-21'),
(64, 236138, 4880833, 'Jaffleman', '8 Place Victor Hugo 94270 Le Kremlin-Bicêtre', NULL, '2025-03-27'),
(65, 235941, 4881385, 'Jaffleman', '25 Rue du Général Leclerc 94270 Le Kremlin-Bicêtre', NULL, '2025-03-27'),
(66, 232617, 4880358, 'Jaffleman', '17 Rue Guy de Gouyon du Verger 94110 Arcueil', NULL, '2025-03-31'),
(67, 233248, 4881229, 'Jaffleman', '2 RUE ALICE MILLIAT\n94110 ARCUEIL', NULL, '2025-04-01'),
(68, 235738, 4880209, 'Jaffleman', '18 Allée du Vercors 94800 Villejuif', NULL, '2025-04-02'),
(69, 232204, 4879469, 'Jaffleman', '23 Rue Ampère 94230 Cachan', NULL, '2025-04-03'),
(70, 236437, 4879933, 'Jaffleman', '49 Rue Jean-Jacques Rousseau 94800 Villejuif', NULL, '2025-04-11'),
(71, 235354, 4881639, 'Jaffleman', '11 Allée des Tanneurs 94250 Gentilly', NULL, '2025-05-05'),
(72, 235391, 4881506, 'Jaffleman', '11 Allée des Tanneurs 94250 Gentilly', NULL, '2025-05-05'),
(73, 236516, 4879777, 'Jaffleman', '79 Rue Jean-Jacques Rousseau 94800 Villejuif', NULL, '2025-05-05'),
(74, 236644, 4879152, 'Jaffleman', '68 Rue Jean Jaurès 94800 Villejuif', NULL, '2025-05-05'),
(75, 236437, 4881509, 'Jaffleman', '37 Rue Roger Salengro 94270 Le Kremlin-Bicêtre', NULL, '2025-05-07'),
(76, 234712, 4879178, 'Jaffleman', '10 CHEMIN DE LA REDOUTE\n\n94800 VILLEJUIF', NULL, '2025-05-09'),
(77, 233993, 4879490, 'Jaffleman', '56 Rue Étienne Dolet 94230 Cachan', NULL, '2025-05-09'),
(78, 236155, 4879466, 'Jaffleman', '41 Avenue Paul Vaillant-Couturier 94800 Villejuif', NULL, '2025-05-12'),
(79, 232772, 4880961, 'Jaffleman', '75 Avenue Laplace 94110 Arcueil', NULL, '2025-05-14'),
(80, 236433, 4880420, 'Jaffleman', '71 Avenue de Paris 94800 Villejuif', NULL, '2025-05-14'),
(81, 236029, 4879941, 'Jaffleman', '42 RUE DE LA CHAPELLE\n94800 VILLEJUIF', NULL, '2025-05-14'),
(82, 234683, 4880435, 'Jaffleman', '10 Rue du Professeur Bergonie 94270 Le Kremlin', NULL, '2025-05-14'),
(83, 236221, 4881469, 'Jaffleman', '14 Rue Roger Salengro 94270 Le Kremlin-Bicêtre', NULL, '2025-05-15'),
(84, 236408, 4880723, 'Jaffleman', '2ter Rue Babeuf 94800 Villejuif', NULL, '2025-05-19'),
(85, 235046, 4880646, 'Jaffleman', '64 Avenue Charles Gide 94270 Le Kremlin-Bicêtre', NULL, '2025-05-22'),
(86, 235775, 4881448, 'Jaffleman', '13 Av du Docteur Antoine Lacroix 94270 Le Kremlin-Bicêtre', NULL, '2025-05-26'),
(87, 236659, 4879049, 'Jaffleman', '100 RUE JEAN JAURES\n94800 VILLEJUIF', NULL, '2025-05-26'),
(88, 237156, 4878359, 'Jaffleman', '72 Rue Jean Lurçat 94800 Villejuif', NULL, '2025-05-27'),
(89, 233258, 4880372, 'Jaffleman', '54 Rue Marius Sidobre 94110 Arcueil', NULL, '2025-05-27'),
(92, 237003, 4880434, 'Jaffleman', '10 Passage Rivière 94800 Villejuif', NULL, '2025-05-28'),
(94, 233381, 4879105, 'Jaffleman', '44 Avenue Dumotel 94230 Cachan', NULL, '2025-06-02'),
(95, 233529, 4879452, 'Jaffleman', '1 Rue Camille Desmoulins 94230 Cachan', NULL, '2025-06-05'),
(96, 235654, 4880213, 'Jaffleman', '10 Allée du Vercors 94800 Villejuif', NULL, '2025-06-05'),
(97, 236862, 4879110, 'Jaffleman', 'unknow', NULL, '2025-06-06'),
(98, 235479, 4877889, 'Jaffleman', '166 Rue de Chevilly 94800 Villejuif', NULL, '2025-06-11'),
(99, 236244, 4879313, 'Jaffleman', '20 Rue du Colonel Marchand 94800 Villejuif', NULL, '2025-06-11'),
(100, 235637, 4880170, 'Jaffleman', '4 Allée du Vercors 94800 Villejuif', NULL, '2025-06-12'),
(103, 235393, 4878872, 'Jaffleman', '104 Rue de Verdun 94800 Villejuif', NULL, '2025-06-13'),
(104, 236670, 4880361, 'Jaffleman', '23 Rue Henri Barbusse 94800 Villejuif', NULL, '2025-06-18'),
(105, 236064, 4881016, 'Jaffleman', '50 Rue Danton 94270 Le Kremlin-Bicêtre', NULL, '2025-06-18'),
(106, 232641, 4879586, 'Jaffleman', '56 Rue Marcel Bonnet 94230 Cachan', NULL, '2025-06-20'),
(107, 235508, 4880261, 'Jaffleman', '3 Rue François Billoux 94800 Villejuif', NULL, '2025-06-23'),
(108, 236290, 4880908, 'Jaffleman', '105 Avenue de Fontainebleau 94270 Le Kremlin-Bicêtre', NULL, '2025-06-24'),
(109, 236707, 4878791, 'Jaffleman', '7 Avenue de Stalingrad 94800 Villejuif', NULL, '2025-06-27'),
(110, 235907, 4881416, 'Jaffleman', '13 Rue du 14 Juillet 94270 Le Kremlin-Bicêtre', NULL, '2025-06-27'),
(111, 233721, 4880789, 'Jaffleman', '6 Avenue Pierre Ronsard 94110 Arcueil', NULL, '2025-06-30'),
(112, 235225, 4880603, 'Jaffleman', '17 Rue Léon Blum 94270 Le Kremlin-Bicêtre', NULL, '2025-07-01'),
(113, 236879, 4879463, 'Jaffleman', '74 BOULEVARD MAXIME GORKI\n94800 VILLEJUIF', NULL, '2025-07-01'),
(114, 236773, 4880451, 'Jaffleman', '27 Rue de la Liberté 94800 Villejuif', NULL, '2025-07-02'),
(115, 233000, 4881199, 'Jaffleman', '2 Rue Antoine Marin 94110 Arcueil', NULL, '2025-07-04'),
(116, 235082, 4881681, '5 rue des 4 tours', NULL, NULL, '2025-07-07'),
(117, 237349, 4878666, 'Jaffleman', '28 Rue du Clos Fleuri 94800 Villejuif', NULL, '2025-07-08'),
(118, 235514, 4877945, 'Jaffleman', '151 RUE DE CHEVILLY 94800 VILLEJUIF', NULL, '2025-09-26'),
(119, 235461, 4878738, 'Jaffleman', '127 Avenue de la République 94800 Villejuif', NULL, '2025-09-26'),
(120, 236716, 4879572, 'Jaffleman', '3 Rue Jean Baptiste Clément 94800 Villejuif', NULL, '2025-09-29'),
(121, 237386, 4878626, 'Jaffleman', '32 Rue du Clos Fleuri 94800 Villejuif', NULL, '2025-09-29');

SELECT pg_catalog.setval('public.acces_id_seq', 156, true);
SELECT pg_catalog.setval('public.marker_id_seq', 121, true);

ALTER TABLE ONLY public.acces ADD CONSTRAINT acces_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.marker ADD CONSTRAINT marker_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.acces ADD CONSTRAINT acces_mk_fkey FOREIGN KEY (mk) REFERENCES public.marker(id) ON DELETE CASCADE;

-- Note: Les clauses GRANT et DEFAULT PRIVILEGES ont été simplifiées
-- car elles s'appliquent désormais nativement à CURRENT_USER.

--
-- Database "maptdpbdd" dump
--

CREATE DATABASE maptdpbdd;

\connect maptdpbdd

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Name: opts; Type: TABLE; Schema: public; Owner: CURRENT_USER
--

CREATE TABLE public.opts (
    id integer NOT NULL,
    opt_label character varying(3)
);

ALTER TABLE public.opts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: reglettes; Type: TABLE; Schema: public; Owner: CURRENT_USER
--

CREATE TABLE public.reglettes (
    id integer NOT NULL,
    reglette_label character varying(5)
);

ALTER TABLE public.reglettes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reglettes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: repartiteurs; Type: TABLE; Schema: public; Owner: CURRENT_USER
--

CREATE TABLE public.repartiteurs (
    id integer NOT NULL,
    code_name character varying(3) NOT NULL,
    long_name text,
    zip integer NOT NULL,
    nbr_salle integer,
    address text
);

ALTER TABLE public.repartiteurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repartiteurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tdps; Type: TABLE; Schema: public; Owner: CURRENT_USER
--

CREATE TABLE public.tdps (
    id integer NOT NULL,
    rep integer NOT NULL,
    reglette_type integer NOT NULL,
    reglette_nbr character varying(2) NOT NULL,
    salle integer NOT NULL,
    rco integer NOT NULL,
    ferme integer NOT NULL,
    level integer NOT NULL,
    opts integer
);

ALTER TABLE public.tdps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tdps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Data for Name: opts; Type: TABLE DATA; Schema: public; Owner: CURRENT_USER
--
INSERT INTO public.opts (id, opt_label) VALUES
(1, 'TNI'), (2, 'TNI'), (3, 'INV'), (4, 'TNI'), (5, 'INV'), (6, 'TNI'), (7, 'INV'), (8, 'TNI'), (9, 'INV'),
(10, 'TNI'), (11, 'INV'), (12, 'TNI'), (13, 'INV'), (14, 'TNI'), (15, 'INV'), (16, 'TNI'), (17, 'INV'),
(18, 'TNI'), (19, 'INV'), (20, 'TNI'), (21, 'INV'), (22, 'TNI'), (23, 'INV'), (24, 'TNI'), (25, 'INV'),
(26, 'TNI'), (27, 'INV'), (28, 'TNI'), (29, 'INV'), (30, 'TNI'), (31, 'INV'), (32, 'TNI'), (33, 'INV'),
(34, 'TNI'), (35, 'INV'), (36, 'TNI'), (37, 'INV'), (38, 'TNI');

--
-- Data for Name: reglettes; Type: TABLE DATA; Schema: public; Owner: CURRENT_USER
--
INSERT INTO public.reglettes (id, reglette_label) VALUES
(1, 'L/INX'), (2, 'R/DEG'), (3, 'A/TEL'), (4, 'T/DEL'), (5, 'T/LIF');

--
-- Data for Name: repartiteurs; Type: TABLE DATA; Schema: public; Owner: CURRENT_USER
--
INSERT INTO public.repartiteurs (id, code_name, long_name, zip, nbr_salle, address) VALUES
(19, 'rep', NULL, 0, 1, NULL),
(1, 'cac', 'Cachan', 94, 1, NULL),
(2, 'cho', 'Choisy-le-Roi', 94, 1, NULL),
(3, 'cnv', 'Cheneviere-sur-Marne', 94, 1, NULL),
(4, 'cpy', 'Champigny-sur-Marne', 94, 2, NULL),
(5, 'chy', 'Chevilly-Larue', 94, 1, NULL),
(6, 'alf', 'Alforville', 94, 2, NULL),
(7, 'bos', 'Creteil (Bossuer)', 94, 1, NULL),
(8, 'bsb', 'Boissy-Saint-Leger', 94, 3, NULL),
(9, 'cre', 'Creteil', 94, 1, NULL),
(10, 'dag', 'Le Perreux-sur-Marne', 94, 1, NULL),
(11, 'dau', 'Vincenne', 94, 1, NULL),
(12, 'fny', 'Val-de-Fonteney', 94, 2, NULL),
(13, 'gra', 'Saint-Maur-des-fossés', 94, 2, NULL),
(14, 'ivr', 'Ivry-sur-Seine', 94, 1, NULL),
(15, 'pom', 'Champigny-sur-Marne', 94, 2, NULL),
(16, 'ram', 'Villjuif', 94, 2, NULL),
(17, 'vit', 'Vitry-sur-Seine', 94, 2, NULL),
(18, 'vsg', 'Villeneuve-Saint-Georges', 94, 1, NULL),
(20, 'pog', NULL, 94, NULL, NULL),
(21, 'pag', NULL, 94, NULL, NULL);

--
-- Data for Name: tdps; Type: TABLE DATA; Schema: public; Owner: CURRENT_USER
--
INSERT INTO public.tdps (id, rep, reglette_type, reglette_nbr, salle, rco, ferme, level, opts) VALUES
(1, 1, 2, 'E8', 1, 1, 37, 6, NULL),
(2, 1, 2, 'E7', 1, 1, 37, 5, NULL),
(3, 1, 2, 'E6', 1, 1, 37, 4, NULL),
(4, 1, 2, 'E5', 1, 1, 37, 3, NULL),
(5, 1, 2, 'E4', 1, 1, 37, 2, NULL),
(6, 1, 2, 'E3', 1, 1, 37, 1, NULL),
(7, 1, 2, 'E2', 1, 1, 35, 7, NULL),
(8, 1, 2, 'E1', 1, 1, 35, 6, NULL),
(9, 1, 2, 'E0', 1, 1, 35, 5, NULL),
(10, 1, 2, 'D9', 1, 1, 35, 4, NULL),
(11, 1, 2, 'D8', 1, 1, 35, 3, NULL),
(12, 1, 2, 'D7', 1, 1, 35, 2, NULL),
(13, 1, 2, 'D6', 1, 1, 35, 1, NULL),
(14, 1, 2, 'D5', 1, 1, 33, 7, NULL),
(15, 1, 2, 'D4', 1, 1, 33, 6, NULL),
(16, 1, 3, 'B3', 1, 1, 33, 5, NULL),
(17, 1, 3, 'B2', 1, 1, 33, 4, NULL),
(18, 1, 3, 'B1', 1, 1, 33, 3, NULL),
(19, 1, 3, 'B0', 1, 1, 33, 2, NULL),
(20, 1, 3, 'A9', 1, 1, 33, 1, NULL),
(21, 1, 3, 'A8', 1, 1, 31, 7, NULL),
(22, 1, 3, 'A7', 1, 1, 31, 6, NULL),
(23, 1, 3, 'A6', 1, 1, 31, 5, NULL),
(24, 1, 3, 'A5', 1, 1, 31, 4, NULL),
(25, 1, 3, 'A4', 1, 1, 31, 3, NULL),
(26, 1, 3, 'A3', 1, 1, 31, 2, NULL),
(27, 1, 3, 'A2', 1, 1, 31, 1, NULL),
(28, 1, 1, 'C3', 1, 1, 27, 7, NULL),
(29, 1, 1, 'C2', 1, 1, 27, 6, NULL),
(30, 1, 1, 'C1', 1, 1, 27, 5, NULL),
(31, 1, 1, 'B6', 1, 1, 27, 4, NULL),
(32, 1, 1, 'B5', 1, 1, 27, 3, NULL),
(33, 1, 1, 'B4', 1, 1, 27, 2, NULL),
(34, 1, 1, '87', 1, 1, 27, 1, NULL),
(35, 1, 2, 'F7', 1, 1, 26, 6, NULL),
(36, 1, 2, 'F6', 1, 1, 26, 5, NULL),
(37, 1, 2, 'F5', 1, 1, 26, 4, NULL),
(38, 1, 2, 'F4', 1, 1, 26, 3, NULL),
(39, 1, 2, 'F3', 1, 1, 26, 2, NULL),
(40, 1, 2, 'F2', 1, 1, 26, 1, NULL),
(41, 1, 2, 'D3', 1, 1, 25, 7, NULL),
(42, 1, 2, 'D2', 1, 1, 25, 6, NULL),
(43, 1, 2, 'D1', 1, 1, 25, 5, NULL),
(44, 1, 1, 'C9', 1, 1, 25, 4, NULL),
(45, 1, 1, 'C8', 1, 1, 25, 3, NULL),
(46, 1, 1, 'C7', 1, 1, 25, 2, NULL),
(47, 1, 1, 'C6', 1, 1, 25, 1, NULL),
(48, 1, 1, '86', 1, 1, 10, 7, NULL),
(49, 1, 1, '85', 1, 1, 10, 6, NULL),
(50, 1, 1, '67', 1, 1, 10, 5, NULL),
(51, 1, 1, '66', 1, 1, 10, 4, NULL),
(52, 1, 1, '65', 1, 1, 10, 3, NULL),
(53, 1, 1, '53', 1, 1, 10, 2, NULL),
(54, 1, 1, '52', 1, 1, 10, 1, NULL),
(55, 1, 1, '51', 1, 1, 9, 7, NULL),
(56, 1, 1, '50', 1, 1, 9, 6, NULL),
(57, 1, 1, '49', 1, 1, 9, 5, NULL),
(58, 1, 1, '48', 1, 1, 9, 4, NULL),
(59, 1, 1, '47', 1, 1, 9, 3, NULL),
(60, 1, 1, '46', 1, 1, 9, 2, NULL),
(61, 1, 1, '45', 1, 1, 9, 1, NULL),
(62, 1, 1, 'C5', 1, 1, 8, 6, NULL),
(63, 1, 1, '28', 1, 1, 8, 5, NULL),
(64, 1, 1, '27', 1, 1, 8, 4, NULL),
(65, 1, 1, '26', 1, 1, 8, 3, NULL),
(66, 1, 1, '25', 1, 1, 8, 2, NULL),
(67, 1, 1, '24', 1, 1, 8, 1, NULL),
(68, 1, 1, '23', 1, 1, 7, 6, NULL),
(69, 1, 1, '20', 1, 1, 7, 5, NULL),
(70, 1, 1, '19', 1, 1, 7, 4, NULL),
(71, 1, 1, '18', 1, 1, 7, 3, NULL),
(72, 1, 1, '17', 1, 1, 7, 2, NULL),
(73, 1, 1, '09', 1, 1, 7, 1, NULL),
(74, 1, 1, 'C4', 1, 1, 6, 7, NULL),
(75, 1, 1, '44', 1, 1, 6, 6, NULL),
(76, 1, 1, '43', 1, 1, 6, 5, NULL),
(77, 1, 1, '42', 1, 1, 6, 4, NULL),
(78, 1, 1, '37', 1, 1, 6, 3, NULL),
(79, 1, 1, '36', 1, 1, 6, 2, NULL),
(80, 1, 1, '35', 1, 1, 6, 1, NULL),
(81, 1, 1, '08', 1, 1, 5, 7, NULL),
(82, 1, 1, '07', 1, 1, 5, 6, NULL),
(83, 1, 1, '06', 1, 1, 5, 5, NULL),
(84, 1, 1, '05', 1, 1, 5, 4, NULL),
(85, 1, 1, '04', 1, 1, 5, 3, NULL),
(86, 1, 1, '03', 1, 1, 5, 2, NULL),
(87, 1, 1, '02', 1, 1, 5, 1, NULL),
(88, 2, 2, 'H2', 1, 1, 23, 8, NULL),
(89, 2, 2, 'H1', 1, 1, 23, 7, NULL),
(90, 2, 2, 'H0', 1, 1, 23, 6, NULL),
(91, 2, 2, 'G9', 1, 1, 23, 5, NULL),
(92, 2, 2, 'G8', 1, 1, 23, 4, NULL),
(93, 2, 2, 'G7', 1, 1, 23, 3, NULL),
(94, 2, 2, 'G6', 1, 1, 23, 2, NULL),
(95, 2, 2, 'G3', 1, 1, 23, 1, NULL),
(96, 2, 2, 'G2', 1, 1, 22, 8, NULL),
(97, 2, 2, 'G1', 1, 1, 22, 7, NULL),
(98, 2, 2, 'F6', 1, 1, 22, 6, NULL),
(99, 2, 2, 'F5', 1, 1, 22, 5, NULL),
(100, 2, 2, 'F4', 1, 1, 22, 4, NULL),
(101, 2, 2, 'F3', 1, 1, 22, 3, NULL),
(102, 2, 2, 'F2', 1, 1, 22, 2, NULL),
(103, 2, 2, 'F1', 1, 1, 22, 1, NULL),
(104, 2, 2, 'F0', 1, 1, 21, 8, NULL),
(105, 2, 2, 'E9', 1, 1, 21, 7, NULL),
(106, 2, 2, 'E8', 1, 1, 21, 6, NULL),
(107, 2, 2, 'E7', 1, 1, 21, 5, NULL),
(108, 2, 2, 'E6', 1, 1, 21, 4, NULL),
(109, 2, 2, 'E5', 1, 1, 21, 3, NULL),
(110, 2, 2, 'E4', 1, 1, 21, 2, NULL),
(111, 2, 2, 'E3', 1, 1, 21, 1, NULL),
(112, 2, 2, 'E2', 1, 1, 20, 8, NULL),
(113, 2, 2, 'E0', 1, 1, 20, 7, NULL),
(114, 2, 2, 'D8', 1, 1, 20, 6, NULL),
(115, 2, 2, 'D7', 1, 1, 20, 5, NULL),
(116, 2, 2, 'D3', 1, 1, 20, 4, NULL),
(117, 2, 2, 'D2', 1, 1, 20, 3, NULL),
(118, 2, 2, 'D1', 1, 1, 20, 2, NULL),
(119, 2, 2, 'D0', 1, 1, 20, 1, NULL),
(120, 2, 2, 'F8', 1, 1, 16, 8, NULL),
(121, 2, 2, 'D6', 1, 1, 16, 7, NULL),
(122, 2, 2, 'D5', 1, 1, 16, 6, NULL),
(123, 2, 2, 'D4', 1, 1, 16, 5, NULL),
(124, 2, 2, 'B8', 1, 1, 16, 4, NULL),
(125, 2, 2, 'B7', 1, 1, 16, 3, NULL),
(126, 2, 2, 'B6', 1, 1, 16, 2, NULL),
(127, 2, 2, 'B5', 1, 1, 16, 1, NULL),
(128, 2, 2, 'C0', 1, 1, 14, 8, NULL),
(129, 2, 2, 'B9', 1, 1, 14, 7, NULL),
(130, 2, 2, 'A7', 1, 1, 14, 6, NULL),
(131, 2, 2, 'A6', 1, 1, 14, 5, NULL),
(132, 2, 2, 'A4', 1, 1, 14, 4, NULL),
(133, 2, 2, 'A3', 1, 1, 14, 3, NULL),
(134, 2, 2, 'A2', 1, 1, 14, 2, NULL),
(135, 2, 2, 'A1', 1, 1, 14, 1, NULL),
(136, 2, 2, 'A0', 1, 1, 13, 8, NULL),
(137, 2, 2, '99', 1, 1, 13, 7, NULL);

-- Fin du script de dump (Tronqué proprement pour l'import d'initialisation)