apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  namespace: maptdp
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "frontend.fullname" . }}-tls

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # FRONTEND (serveur Nginx)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" . }}-srv
                port:
                  number: {{ .Values.service.port }}