apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso-argocd
  namespace: argocd
  annotations:
    argocd.openshift.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/jaffleman/New_MapTdp.git'
    targetRevision: main
    path: deploy/apps/infra/vso/secrets/vso-argocd

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bootstrap

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: secrets.hashicorp.com
      kind: VaultStaticSecret
      jsonPointers:
        - /status
        - /spec/refreshInterval