apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso-grafana
  namespace: argocd
  annotations:
    argocd.openshift.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/jaffleman/maptdp-gitops.git'
    targetRevision: bootstrap-infra
    path: apps/prod/infra/vso/secrets/vso-grafana

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: secrets.hashicorp.com
      kind: VaultStaticSecret
      jsonPointers:
        - /status
        - /spec/refreshInterval