apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-jwt-auth
  namespace: maptdp-staging
spec:
  vaultConnectionRef: vault-connection-maptdp
  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: db-role
    serviceAccount: vso-app-sa