apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-cronjob
  namespace: maptdp-staging

spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
             app.kubernetes.io/component: backup
        spec:
          restartPolicy: OnFailure

          containers:
            - name: postgres-backup

              image: docker.io/jaffleman971/postgres-backup:1.0
              imagePullPolicy: IfNotPresent

              env:
                # PostgreSQL
                - name: PGHOST
                  value: maptdp-db

                - name: PGPORT
                  value: "5432"

                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: maptdp-db-auth
                      key: user

                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: maptdp-db-auth
                      key: password

                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: maptdp-db-auth
                      key: db

                # AWS S3
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: postgres-s3-auth
                      key: access_key

                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: postgres-s3-auth
                      key: secret_key

                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: postgres-s3-auth
                      key: region

                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: postgres-s3-auth
                      key: bucket

                - name: S3_PREFIX
                  valueFrom:
                    secretKeyRef:
                      name: postgres-s3-auth
                      key: prefix

              command:
                - /bin/sh
                - -c

              args:
                - |
                  set -euo pipefail

                  DATE=$(date +%Y%m%d_%H%M%S)
                  FILE="backup_${PGDATABASE}_${DATE}.sql.gz"

                  echo "==================================="
                  echo "Verification identite AWS"
                  echo "==================================="

                  aws sts get-caller-identity

                  echo "==================================="
                  echo "Creation du dump PostgreSQL"
                  echo "==================================="

                  pg_dump \
                    -h "${PGHOST}" \
                    -p "${PGPORT}" \
                    -U "${PGUSER}" \
                    "${PGDATABASE}" \
                    | gzip > "/tmp/${FILE}"

                  ls -lh "/tmp/${FILE}"

                  echo "==================================="
                  echo "Upload vers S3"
                  echo "==================================="

                  aws s3 cp \
                    "/tmp/${FILE}" \
                    "s3://${S3_BUCKET}/${S3_PREFIX}/${FILE}"

                  echo "==================================="
                  echo "Verification du fichier distant"
                  echo "==================================="

                  aws s3 ls \
                    "s3://${S3_BUCKET}/${S3_PREFIX}/${FILE}"

                  echo "==================================="
                  echo "Sauvegarde terminee avec succes"
                  echo "==================================="
