apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maptdp-db-dev
  namespace: argocd
  annotations:
    # --- ArgoCD Image Updater ---
    argocd-image-updater.argoproj.io/image-list: db=docker.io/jaffleman971/maptdp-db

    # Stratégie de mise à jour
    argocd-image-updater.argoproj.io/db.update-strategy: semver

    # Autorise les tags 16.x
    argocd-image-updater.argoproj.io/db.allow-tags: regexp:^16\.[0-9]+$

    # --- GitOps ---
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: dev

    argocd-image-updater.argoproj.io/write-back-target: helmvalues
    argocd-image-updater.argoproj.io/write-back-path: charts/maptdp-db
    argocd-image-updater.argoproj.io/helm-values-file: values.yaml

    # --- Mapping Helm obligatoire ---
    argocd-image-updater.argoproj.io/db.helm.image-name: db.image.repository
    argocd-image-updater.argoproj.io/db.helm.image-tag: db.image.tag

spec:
  project: default

  source:
    repoURL: https://github.com/jaffleman/maptdp-gitops.git
    targetRevision: dev
    path: charts/maptdp-db
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: maptdp-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
