helm:
  parameters:
  - name: frontend.image.repository
    value: docker.io/jaffleman971/maptdp-frontend
    forcestring: true
  - name: frontend.image.tag
    value: staging-sha-1781867174
    forcestring: true
