helm:
  parameters:
  - name: frontend.image.repository
    value: docker.io/jaffleman971/maptdp-frontend
    forcestring: true
  - name: frontend.image.tag
    value: dev-sha-228deb7
    forcestring: true
