helm:
  parameters:
  - name: frontend.image.repository
    value: docker.io/jaffleman971/maptdp-frontend
    forcestring: true
  - name: frontend.image.tag
    value: dev-sha-907530b
    forcestring: true
