global:
  imagePullSecrets: []

enabled: true
frontend:
  image:
    repository: docker.io/jaffleman971/maptdp-frontend
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "maptdp.dev.jaffleman.tech"
  tls: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "le"

runtimeConfig:
  apiBaseUrl: "https://api.dev.jaffleman.tech"

resources:
  requests: 
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi