replicaCount: 1

ingress:
  host: "maptdp.dev.jaffleman.tech"

runtimeConfig:
  apiBaseUrl: "https://api.dev.jaffleman.tech"
env:
  - name: PORT
    value: "80"
  - name: NODENV
    value: "dev"
  - name: LOG_LEVEL
    value: "debug"
