apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maptdp-db-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: db=docker.io/jaffleman971/maptdp-db

    # ✅ stratégie adaptée pipeline actuel
    argocd-image-updater.argoproj.io/db.update-strategy: semver

    # ✅ accepte tous les tags
    argocd-image-updater.argoproj.io/db.allow-tags: regexp:^16\.[0-9]+$
    
    # ✅ GitOps
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: dev

    # ✅ mapping Helm (OBLIGATOIRE)
    argocd-image-updater.argoproj.io/db.helm.image-name: db.image.repository
    argocd-image-updater.argoproj.io/db.helm.image-tag: db.image.tag

spec:
  project: default
  source:
    repoURL: https://github.com/jaffleman/maptdp-database.git
    targetRevision: dev
    path: chart/maptdp-db
  destination:
    server: https://kubernetes.default.svc
    namespace: maptdp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true