apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maptdp-frontend-dev
  namespace: argocd

  annotations:
    # ✅ image à surveiller (sans semver)
    argocd-image-updater.argoproj.io/image-list: |
      frontend=docker.io/jaffleman971/maptdp-frontend

    # ✅ stratégie : prendre le dernier tag disponible
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build

    # ✅ filtrer uniquement les tags SHA
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^sha-[a-f0-9]{7}$


    # ✅ écriture dans Git (GitOps)
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: dev
    # ✅ mapping Helm → où modifier image
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag

spec:
  project: default

  source:
    repoURL: https://github.com/jaffleman/maptdp-frontend.git
    targetRevision: dev
    path: chart/maptdp-frontend
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: maptdp-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true