apiVersion: v1
kind: Secret
metadata:
  name: maptdp-backend-env
  namespace: maptdp
type: Opaque
stringData:
  DATABASE_URL: "postgres://extjaff:${POSTGRES_PASSWORD}@maptdp-db.maptdp.svc.cluster.local:5432/maptdpbdd"