- name: Bootstrap Kubernetes + ArgoCD + Vault integration
  hosts: k3s_nodes
  become: true

  vars_files:
    - ../../credentials.yml   # 🔐 chiffré avec Ansible Vault

  vars:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml

  roles:
    # 🔐 Sécurité système
    - role: ssh_hardening
      tags: [ssh, security]

    # Pré-requis système
    - role: k3s_prereqs
      tags: [k3s, prereqs]

    # ⚙️ Installation cluster K3s
    - role: k3s_server
      tags: [k3s]

    # Installation de python
    - role: python_prereqs
      tags: [pip]

    # 📦 Installation Helm
    - role: helm
      tags: [helm]

    # 🚀 Installation ArgoCD
    - role: argocd
      tags: [argocd]

    # 🔐 Injection des secrets Vault (TRÈS IMPORTANT ici)
    - role: vault
      tags: [vault, secrets]

    # 🚀 Bootstrap GitOps (attente + root-app)
    - role: argocd_bootstrapv2
      tags: [argocd, bootstrap]
