helm:
  parameters:
  - name: backend.image.repository
    value: docker.io/jaffleman971/maptdp-backend
    forcestring: true
  - name: backend.image.tag
    value: dev-sha-5a5a66b
    forcestring: true
