helm:
  parameters:
  - name: backend.image.repository
    value: docker.io/jaffleman971/maptdp-backend
    forcestring: true
  - name: backend.image.tag
    value: staging-sha-1784575443
    forcestring: true
