# deploy/charts/maptdp/values.yaml
ingress:
  host: ""

global:
  imagePullSecrets: []

enabled: true
backend:
  image:
    repository: docker.io/jaffleman971/maptdp-backend
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env: []
envFrom: []

livenessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }